name: Frontend (Coverage)

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    defaults:
      run:
        working-directory: javascript
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      NODE_PATH: src/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run coverage
      - name: Upload to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        working-directory: .
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Create dummy javascript build folder
        run: mkdir javascript/build
        working-directory: .
      - name: Build with Maven
        working-directory: .
        env:
          TEST_PROPERTIES: ${{ secrets.TEST_PROPERTIES }}
        run: mvn -B test jacoco:report -Dskip.npm
      - name: Upload to Codecov
        working-directory: .
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
